// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLi2ytr_xPeiP8aSs-LvpeWtZszBmhck',
    appId: '1:185019085442:web:a6d46c0b01f72041b87a9b',
    messagingSenderId: '185019085442',
    projectId: 'outfitory',
    authDomain: 'outfitory.firebaseapp.com',
    storageBucket: 'outfitory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdh5XIMiz5sFDeBXQyJjymOUzwVEeGwzM',
    appId: '1:185019085442:android:5e5cb09d6f5306f7b87a9b',
    messagingSenderId: '185019085442',
    projectId: 'outfitory',
    storageBucket: 'outfitory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUwjOdZMvz-oWcQCxuIS4DygejKhGSDPE',
    appId: '1:185019085442:ios:4eb1c1f98c465896b87a9b',
    messagingSenderId: '185019085442',
    projectId: 'outfitory',
    storageBucket: 'outfitory.firebasestorage.app',
    iosBundleId: 'com.example.outfitory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUwjOdZMvz-oWcQCxuIS4DygejKhGSDPE',
    appId: '1:185019085442:ios:4eb1c1f98c465896b87a9b',
    messagingSenderId: '185019085442',
    projectId: 'outfitory',
    storageBucket: 'outfitory.firebasestorage.app',
    iosBundleId: 'com.example.outfitory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHLi2ytr_xPeiP8aSs-LvpeWtZszBmhck',
    appId: '1:185019085442:web:570314f614a94201b87a9b',
    messagingSenderId: '185019085442',
    projectId: 'outfitory',
    authDomain: 'outfitory.firebaseapp.com',
    storageBucket: 'outfitory.firebasestorage.app',
  );
}
